import crypto from 'node:crypto';
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { bundle } from '@remotion/bundler';
import { renderMedia, selectComposition } from '@remotion/renderer';

interface ManifestAudio {
  id: string;
  file_path: string;
  duration_sec: number;
  voice?: string;
  staticSrc?: string;
}

interface ExistingManifest {
  projectName: string;
  footerText?: string;
  scenes: Array<Record<string, any>>;
  audioSegments: ManifestAudio[];
  visualStyle?: string;
  motionStyle?: string;
  [key: string]: unknown;
}

function argument(name: string, fallback = '') {
  const exact = process.argv.indexOf(name);
  if (exact >= 0) return process.argv[exact + 1] || fallback;
  const prefix = `${name}=`;
  return process.argv.find((value) => value.startsWith(prefix))?.slice(prefix.length) || fallback;
}

function atempoFilter(speed: number) {
  const factors: number[] = [];
  let remaining = speed;
  while (remaining > 2) {
    factors.push(2);
    remaining /= 2;
  }
  while (remaining < 0.5) {
    factors.push(0.5);
    remaining /= 0.5;
  }
  factors.push(remaining);
  return factors.map((factor) => `atempo=${factor.toFixed(6)}`).join(',');
}

async function main() {
  const manifestPath = path.resolve(argument('--manifest'));
  const output = path.resolve(argument('--output', 'public/vibing/outputs/manifest-render.mp4'));
  const targetDuration = Number(argument('--duration', '0')) || 0;
  if (!fs.existsSync(manifestPath)) throw new Error(`manifest not found: ${manifestPath}`);

  const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8')) as ExistingManifest;
  if (!manifest.scenes?.length || !manifest.audioSegments?.length) {
    throw new Error('manifest must include scenes and audioSegments');
  }

  const sourceDuration = manifest.audioSegments.reduce((sum, item) => sum + Number(item.duration_sec || 0), 0);
  const speed = targetDuration > 0 ? sourceDuration / targetDuration : 1;
  const renderId = crypto.createHash('sha1').update(`${manifestPath}:${targetDuration}`).digest('hex').slice(0, 10);
  const publicAudioDir = path.resolve('public', 'vibing', 'manifest-audio', renderId);
  fs.mkdirSync(publicAudioDir, { recursive: true });

  console.log(`[manifest] ${manifestPath}`);
  console.log(`[timing] source=${sourceDuration.toFixed(2)}s target=${targetDuration || sourceDuration}s speed=${speed.toFixed(4)}x`);
  const audioSegments = manifest.audioSegments.map((audio, index) => {
    const source = path.resolve(audio.file_path);
    if (!fs.existsSync(source)) throw new Error(`audio not found: ${source}`);
    const extension = path.extname(source) || '.mp3';
    const destinationName = `${audio.id || `scene-${index + 1}`}${extension}`;
    const destination = path.join(publicAudioDir, destinationName);
    if (Math.abs(speed - 1) > 0.005) {
      execFileSync('ffmpeg', ['-y', '-i', source, '-filter:a', atempoFilter(speed), '-vn', destination], {
        stdio: 'pipe',
        timeout: 120_000,
      });
    } else {
      fs.copyFileSync(source, destination);
    }
    return {
      ...audio,
      file_path: destination,
      duration_sec: Number(audio.duration_sec) / speed,
      staticSrc: `vibing/manifest-audio/${renderId}/${destinationName}`,
    };
  });

  const scenes = manifest.scenes.map((scene, index) => ({
    ...scene,
    durationSec: audioSegments[index]?.duration_sec || scene.durationSec,
  }));
  const totalDuration = audioSegments.reduce((sum, item) => sum + item.duration_sec, 0);
  const inputProps = {
    scenes,
    audioSegments,
    projectName: manifest.projectName,
    footerText: manifest.footerText || 'generated by vibing vidio',
    visualStyle: manifest.visualStyle,
    motionStyle: manifest.motionStyle,
  };

  const derivedManifestPath = output.replace(/\.mp4$/i, '.manifest.json');
  fs.mkdirSync(path.dirname(output), { recursive: true });
  fs.writeFileSync(derivedManifestPath, JSON.stringify({
    ...manifest,
    scenes,
    audioSegments,
    targetDurationSec: totalDuration,
    timing: { sourceDurationSec: sourceDuration, speed, normalizedDurationSec: totalDuration },
  }, null, 2), 'utf8');

  const serveUrl = await bundle({ entryPoint: path.resolve('src', 'index.ts') });
  const composition = await selectComposition({ serveUrl, id: 'ProjectShowcase', inputProps });
  (composition as any).durationInFrames = Math.round(totalDuration * 30);
  await renderMedia({
    composition,
    serveUrl,
    codec: 'h264',
    outputLocation: output,
    inputProps,
    onProgress: ({ progress }) => process.stdout.write(`\r[render] ${Math.round(progress * 100)}%`),
  });
  process.stdout.write('\n');
  console.log(`[done] ${output}`);
  console.log(`[duration] ${totalDuration.toFixed(2)}s`);
  console.log(`[derived-manifest] ${derivedManifestPath}`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
